export const dummyTeamMembers = [
  {
    id: "1",
    slug: "alex-morgan",
    name: "Alex Morgan",
    role: "CEO & Founder",
    initials: "AM",
    avatarColor: "from-blue-500 to-indigo-600",
    color: "from-blue-500 to-indigo-600",
    order: 0,
    bio: "15+ years of experience in software engineering and product leadership.\n\nAlex founded CloudWent with a vision to build scalable digital products that drive real impact. Previously led engineering teams at Fortune 500 companies.",
    image: "/team/alex.jpg",
    location: "San Francisco, CA",
    experience: "15+ Years",
    email: "alex@cloudwent.com",
    linkedin: "https://linkedin.com",
    twitter: "https://twitter.com",
    github: "https://github.com",
    team: "leadership",
    expertise: ["Strategy", "Product", "Leadership"],
    skills: ["React", "Node.js", "Python"],
    certifications: ["AWS Solutions Architect"],
    experience_timeline: [
      { period: "2020 - Present", title: "CEO & Founder", company: "CloudWent", desc: "Building a world-class engineering consultancy focused on scalable digital products." },
      { period: "2015 - 2020", title: "VP of Engineering", company: "TechCorp Inc.", desc: "Led a team of 50+ engineers building enterprise SaaS platforms." },
      { period: "2010 - 2015", title: "Senior Software Engineer", company: "StartupXYZ", desc: "Built core platform features that scaled to millions of users." },
    ],
    education: [
      { degree: "M.S. Computer Science", school: "Stanford University", years: "2008 - 2010" },
      { degree: "B.S. Computer Science", school: "UC Berkeley", years: "2004 - 2008" },
    ],
    projects: [
      { name: "CloudWent Platform", type: "SaaS", desc: "End-to-end product engineering platform.", tags: ["React", "Node.js", "AWS"], badge: "Live" },
    ],
  },
  {
    id: "2",
    slug: "jordan-lee",
    name: "Jordan Lee",
    role: "CTO",
    initials: "JL",
    avatarColor: "from-emerald-500 to-teal-600",
    color: "from-emerald-500 to-teal-600",
    order: 1,
    bio: "Expert in cloud architecture and distributed systems with a passion for innovation.\n\nJordan drives the technical vision at CloudWent, ensuring we stay at the cutting edge of technology.",
    image: "/team/jordan.jpg",
    location: "New York, NY",
    experience: "12+ Years",
    email: "jordan@cloudwent.com",
    linkedin: "https://linkedin.com",
    twitter: "https://twitter.com",
    github: "https://github.com",
    team: "leadership",
    expertise: ["Cloud", "Architecture", "AI"],
    skills: ["AWS", "Kubernetes", "Python"],
    certifications: ["Google Cloud Professional"],
    experience_timeline: [
      { period: "2020 - Present", title: "CTO", company: "CloudWent", desc: "Defining technical strategy and leading architecture decisions." },
      { period: "2015 - 2020", title: "Principal Architect", company: "CloudScale", desc: "Designed cloud infrastructure serving 10M+ daily users." },
    ],
    education: [
      { degree: "M.S. Distributed Systems", school: "MIT", years: "2011 - 2013" },
    ],
    projects: [
      { name: "AI Pipeline", type: "AI/ML", desc: "Real-time ML inference pipeline for SaaS products.", tags: ["Python", "TensorFlow", "Kafka"], badge: "Live" },
    ],
  },
  {
    id: "3",
    slug: "taylor-wright",
    name: "Taylor Wright",
    role: "Lead Designer",
    initials: "TW",
    avatarColor: "from-violet-500 to-purple-600",
    color: "from-violet-500 to-purple-600",
    order: 2,
    bio: "Award-winning designer focused on creating intuitive and beautiful user experiences.\n\nTaylor brings a human-centered approach to every project, ensuring products are both functional and delightful.",
    image: "/team/taylor.jpg",
    location: "London, UK",
    experience: "8+ Years",
    email: "taylor@cloudwent.com",
    linkedin: "https://linkedin.com",
    twitter: "https://twitter.com",
    github: "https://github.com",
    team: "design",
    expertise: ["UX", "UI", "Design Systems"],
    skills: ["Figma", "Adobe XD", "CSS"],
    certifications: ["Google UX Design"],
    experience_timeline: [
      { period: "2021 - Present", title: "Lead Designer", company: "CloudWent", desc: "Leading design for all client projects and internal products." },
      { period: "2017 - 2021", title: "Senior UX Designer", company: "DesignStudio", desc: "Led UX for Fortune 500 clients including redesigns of banking apps." },
    ],
    education: [
      { degree: "B.F.A. Graphic Design", school: "Rhode Island School of Design", years: "2013 - 2017" },
    ],
    projects: [
      { name: "Design System", type: "Design", desc: "Comprehensive design system used across 20+ products.", tags: ["Figma", "Storybook", "CSS"], badge: "Live" },
    ],
  },
  {
    id: "4",
    slug: "casey-patel",
    name: "Casey Patel",
    role: "Senior Developer",
    initials: "CP",
    avatarColor: "from-amber-500 to-orange-600",
    color: "from-amber-500 to-orange-600",
    order: 3,
    bio: "Full-stack developer with expertise in modern JavaScript frameworks and cloud infrastructure.\n\nCasey specializes in building high-performance web applications with clean, maintainable code.",
    image: "/team/casey.jpg",
    location: "Toronto, CA",
    experience: "7+ Years",
    email: "casey@cloudwent.com",
    linkedin: "https://linkedin.com",
    twitter: "https://twitter.com",
    github: "https://github.com",
    team: "engineering",
    expertise: ["Frontend", "Backend", "DevOps"],
    skills: ["React", "Next.js", "AWS"],
    certifications: ["AWS Developer"],
    experience_timeline: [
      { period: "2022 - Present", title: "Senior Developer", company: "CloudWent", desc: "Leading frontend development for enterprise clients." },
      { period: "2018 - 2022", title: "Full-Stack Developer", company: "WebAgency", desc: "Built 50+ websites and web applications for clients worldwide." },
    ],
    education: [
      { degree: "B.S. Software Engineering", school: "University of Toronto", years: "2014 - 2018" },
    ],
    projects: [
      { name: "E-Commerce Platform", type: "Web", desc: "High-performance e-commerce platform handling 100K+ daily users.", tags: ["Next.js", "Node.js", "PostgreSQL"], badge: "Live" },
    ],
  },
  {
    id: "5",
    slug: "riley-kim",
    name: "Riley Kim",
    role: "AI Engineer",
    initials: "RK",
    avatarColor: "from-rose-500 to-pink-600",
    color: "from-rose-500 to-pink-600",
    order: 4,
    bio: "Machine learning specialist focused on NLP and computer vision solutions.\n\nRiley brings cutting-edge AI expertise to client projects, from chatbots to computer vision systems.",
    image: "/team/riley.jpg",
    location: "Seoul, KR",
    experience: "6+ Years",
    email: "riley@cloudwent.com",
    linkedin: "https://linkedin.com",
    twitter: "https://twitter.com",
    github: "https://github.com",
    team: "engineering",
    expertise: ["Machine Learning", "NLP", "Computer Vision"],
    skills: ["Python", "TensorFlow", "PyTorch"],
    certifications: ["TensorFlow Developer"],
    experience_timeline: [
      { period: "2022 - Present", title: "AI Engineer", company: "CloudWent", desc: "Building AI solutions for clients across industries." },
      { period: "2019 - 2022", title: "ML Engineer", company: "AIStartup", desc: "Developed NLP models for customer service automation." },
    ],
    education: [
      { degree: "M.S. Artificial Intelligence", school: "KAIST", years: "2017 - 2019" },
      { degree: "B.S. Computer Science", school: "Seoul National University", years: "2013 - 2017" },
    ],
    projects: [
      { name: "Chatbot Platform", type: "AI/ML", desc: "Enterprise chatbot platform using LLMs and RAG.", tags: ["Python", "LangChain", "OpenAI"], badge: "Live" },
    ],
  },
];
